# frozen_string_literal: true

Rails.application.routes.draw do
  # ── OpenAPI ───────────────────────────────────────────────────────────────
  # Rswag::Api serves the raw JSON spec (generated by rswag:specs:swaggerize).
  #   GET /openapi/v1/swagger.json
  mount Rswag::Api::Engine => '/openapi'

  # Redocly docs — served as a static file from public/api-docs/index.html.
  # Rails serves public/ automatically; this explicit route provides a clean URL.
  #   GET /api-docs  →  public/api-docs/index.html
  get '/api-docs', to: proc { |_env|
    html = Rails.root.join('public/api-docs/index.html').read
    [200, { 'Content-Type' => 'text/html; charset=utf-8' }, [html]]
  }

  # ── API v1 ────────────────────────────────────────────────────────────────
  namespace :api do
    namespace :v1 do
      # Current user identity & profile
      get  'me', to: 'me#show'

      # Solar readings (all authenticated users, subject to query_limit_days)
      get 'solar/readings', to: 'solar#readings'

      # User management (admin + manager)
      resources :users, only: %i[index show destroy] do
        patch :query_limit, on: :member
        patch :reactivate,  on: :member
      end

      # Invitations (admin + manager)
      resources :invitations, only: %i[create]
    end
  end

  # ── Health check ──────────────────────────────────────────────────────────
  get '/health', to: proc { [200, {}, [{ status: 'ok' }.to_json]] }
end
